# Generated by Django 2.2.4 on 2019-08-15 20:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='age',
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='birth date'),
        ),
    ]
