# Generated by Django 2.2.4 on 2019-08-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190815_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='avatar',
            field=models.FileField(blank=True, default='avatars/default.png', upload_to='avatars/'),
        ),
    ]
