# Generated by Django 2.2.4 on 2019-09-03 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_auto_20190830_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='description',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
