# Generated by Django 2.2.4 on 2019-09-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_auto_20190903_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default='test-title', max_length=100),
            preserve_default=False,
        ),
    ]
