# Generated by Django 2.2.4 on 2019-09-04 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0012_auto_20190904_1751'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
