# Generated by Django 2.2.4 on 2019-09-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0015_auto_20190904_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
